# Generated by Django 5.1.1 on 2024-10-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_remove_studentprofile_user_college_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='tours/')),
            ],
        ),
    ]
